import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'mr' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    instructors: 'Instructors',
    students: 'Students',
    profile: 'My Profile',
    lessonPlan: 'Lesson Plan',
    demoPlan: 'Demo Plan',
    monthlyPlan: 'Monthly Plan',
    yearlyPlan: 'Yearly Plan',
    monthlyAssess: 'Monthly Assess',
    internalAssess: 'Internal Assess',
    examForm: 'Exam Form',
    attendance: 'Attendance',
    customForms: 'Custom Registers',
    logout: 'Log out',
    settings: 'Settings',
    appName: 'ITI Instructor MS',
    welcome: 'Welcome back',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    loading: 'Loading...',
    print: 'Print',
    generate: 'Generate',
    dailyDiary: 'Daily Diary',
    instructorDashboard: 'Instructor Dashboard',
    adminDashboard: 'Admin Dashboard',
    profilePending: 'Profile Pending',
    welcomeUser: 'Welcome, {name}!',
    contactAdminEmail: 'Your instructor profile is not yet linked to this account. Please contact the administrator to link your profile using your email: ',
    gettingStarted: 'Getting Started',
    profileLinkedInfo: 'Once your profile is linked, you will be able to see your trade assignments, experience details, and other professional information here.',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    tradeDept: 'Trade/Department',
    qualification: 'Qualification',
    experience: 'Experience',
    phoneNumber: 'Phone Number',
    joiningDate: 'Joining Date',
    myProfileDetails: 'My Profile Details',
    currentStatus: 'Current Status',
    assignedTrade: 'Assigned Trade',
    profileUpToDateInfo: 'Your profile is up to date. If you need to change any information, please contact the ITI Admin.',
    quickLinks: 'Quick Links',
    viewTradeSyllabus: 'View Trade Syllabus',
    attendanceRegister: 'Attendance Register',
    studentProgress: 'Student Progress',
    active: 'Active',
    years: 'Years',
    notSpecified: 'Not specified',
    dashboardOverview: 'Dashboard Overview',
    welcomeAppInfo: 'Welcome to the ITI Instructor Management System.',
    totalInstructors: 'Total Instructors',
    inactive: 'Inactive',
    tradesCovered: 'Trades Covered',
    aboutSystem: 'About the System',
    systemDescription1: 'This system is designed to streamline the management of instructors at Industrial Training Institutes (ITI). It allows administrators to maintain a comprehensive database of teaching staff, their qualifications, assigned trades, and employment status.',
    systemDescription2: 'Key features include:',
    centralizedDb: 'Centralized Instructor Database',
    tradeAllocation: 'Trade-wise Staff Allocation',
    statusTracking: 'Real-time Status Tracking',
    rbac: 'Secure Role-based Access Control',
    quickActions: 'Quick Actions',
    addTradeInfo: 'Need to add a new trade?',
    generateMonthlyReport: 'Generate monthly report',
    contactAdmin: 'Contact Admin',
    comingSoon: 'Coming Soon',
    instituteName: 'Institute Name',
    batch: 'Batch',
    lessonName: 'Lesson Name',
    lessonNo: 'Lesson No',
    duration: 'Duration',
    plannedDate: 'Planned Date',
    procedure: 'Procedure',
    infoPoints: 'Information Points',
    visualAids: 'Visual Aids',
    addRow: 'Add Row',
    deleteRow: 'Delete Row',
    aiGenerate: 'AI Generate Content',
    savePlan: 'Save Lesson Plan',
    updateRecord: 'Update Record',
    step: 'Step',
    details: 'Details',
    back: 'Back',
    min: 'Min',
    hrs: 'Hrs',
    instructorPanel: 'Instructor Panel',
    administration: 'Administration',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    instructors: 'शिक्षक',
    students: 'विद्यार्थी',
    profile: 'माझे प्रोफाइल',
    lessonPlan: 'धडा नियोजन (Lesson Plan)',
    demoPlan: 'प्रात्यक्षिक नियोजन (Demo Plan)',
    monthlyPlan: 'मासिक नियोजन',
    yearlyPlan: 'वार्षिक नियोजन',
    monthlyAssess: 'मासिक मूल्यमापन',
    internalAssess: 'अंतर्गत मूल्यमापन',
    examForm: 'परीक्षा फॉर्म',
    attendance: 'उपस्थिती',
    customForms: 'सानुकूल रजिस्टर',
    logout: 'बाहेर पडा (Log out)',
    settings: 'सेटिंग्ज',
    appName: 'आयटीआय इन्स्ट्रक्टर एमएस',
    welcome: 'पुन्हा स्वागत आहे',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    edit: 'संपादन करा',
    delete: 'हटवा',
    loading: 'लोड होत आहे...',
    print: 'प्रिंट',
    generate: 'व्युत्पन्न करा',
    dailyDiary: 'दैनिक डायरी',
    instructorDashboard: 'शिक्षक डॅशबोर्ड',
    adminDashboard: 'प्रशासक डॅशबोर्ड',
    profilePending: 'प्रोफाइल प्रलंबित',
    welcomeUser: 'स्वागत आहे, {name}!',
    contactAdminEmail: 'तुमचे शिक्षक प्रोफाइल अजून या खात्याशी लिंक केलेले नाही. कृपया तुमच्या ईमेलचा वापर करून प्रोफाईल लिंक करण्यासाठी प्रशासकाशी संपर्क साधा: ',
    gettingStarted: 'सुरुवात करा',
    profileLinkedInfo: 'एकदा तुमचे प्रोफाइल लिंक झाले की, तुम्ही तुमची ट्रेड असाइनमेंट, अनुभवाचा तपशील आणि इतर व्यावसायिक माहिती येथे पाहू शकाल.',
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल पत्ता',
    tradeDept: 'ट्रेड/विभाग',
    qualification: 'पात्रता',
    experience: 'अनुभव',
    phoneNumber: 'फोन नंबर',
    joiningDate: 'रुजू होण्याची तारीख',
    myProfileDetails: 'माझे प्रोफाइल तपशील',
    currentStatus: 'वर्तमान स्थिती',
    assignedTrade: 'नियुक्त ट्रेड',
    profileUpToDateInfo: 'तुमचे प्रोफाइल अद्ययावत आहे. तुम्हाला कोणतीही माहिती बदलायची असल्यास, कृपया आयटीआय प्रशासकाशी संपर्क साधा.',
    quickLinks: 'क्विक लिंक्स',
    viewTradeSyllabus: 'ट्रेड अभ्यासक्रम पहा',
    attendanceRegister: 'उपस्थिती नोंदणी',
    studentProgress: 'विद्यार्थी प्रगती',
    active: 'सक्रिय',
    years: 'वर्षे',
    notSpecified: 'निर्दिष्ट केलेले नाही',
    dashboardOverview: 'डॅशबोर्ड विहंगावलोकन',
    welcomeAppInfo: 'आयटीआय इन्स्ट्रक्टर मॅनेजमेंट सिस्टममध्ये आपले स्वागत आहे.',
    totalInstructors: 'एकूण शिक्षक',
    inactive: 'निष्क्रिय',
    tradesCovered: 'कव्हर केलेले ट्रेड्स',
    aboutSystem: 'सिस्टम बद्दल',
    systemDescription1: 'ही प्रणाली औद्योगिक प्रशिक्षण संस्थांमधील (ITI) शिक्षकांचे व्यवस्थापन सुलभ करण्यासाठी आणि अद्ययावत ठेवण्यासाठी डिझाइन केलेली आहे.',
    systemDescription2: 'मुख्य वैशिष्ट्यांमध्ये हे समाविष्ट आहे:',
    centralizedDb: 'केंद्रीकृत शिक्षक डेटाबेस',
    tradeAllocation: 'ट्रेड-नुसार कर्मचारी वाटप',
    statusTracking: 'रिअल-टाइम स्टेटस ट्रॅकिंग',
    rbac: 'सुरक्षित भूमिका-आधारित प्रवेश नियंत्रण',
    quickActions: 'त्वरीत कृती',
    addTradeInfo: 'नवीन ट्रेड जोडण्याची गरज आहे?',
    generateMonthlyReport: 'मासिक अहवाल तयार करा',
    contactAdmin: 'प्रशासकाशी संपर्क साधा',
    comingSoon: 'लवकरच येत आहे',
    instituteName: 'संस्थेचे नाव',
    batch: 'बॅच',
    lessonName: 'पाठाचे नाव',
    lessonNo: 'पाठ क्र.',
    duration: 'वेळ (कालावधी)',
    plannedDate: 'नियोजित तारीख',
    procedure: 'मुद्दे (Procedure)',
    infoPoints: 'माहिती विषयक मुद्दे',
    visualAids: 'दृश्य सूचना',
    addRow: 'रो जोडा',
    deleteRow: 'रो हटवा',
    aiGenerate: 'एआय द्वारे तयार करा',
    savePlan: 'नियोजन जतन करा',
    updateRecord: 'रेकॉर्ड अपडेट करा',
    step: 'पाऊल',
    details: 'तपशील',
    back: 'मागे',
    min: 'मििनटे',
    hrs: 'तास',
    selectTrade: 'ट्रेड निवडा',
    district: 'जिल्हा',
    objectives: 'उद्दिष्टे',
    skillsLearned: 'शिकलेली कौशल्ये',
    toolsUsed: 'वापरलेली साधने/साहित्य',
    motivation: 'प्रेरणा (Motivation)',
    presentation: 'सादरीकरण',
    result: 'निकाल/निष्कर्ष',
    studentInvolvement: 'विद्यार्थ्यांचा सहभाग',
    spotHints: 'स्पॉट हिंट्स',
    instructorPanel: 'शिक्षक पॅनेल',
    administration: 'प्रशासन',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    instructors: 'प्रशिक्षक',
    students: 'छात्र',
    profile: 'मेरी प्रोफाइल',
    lessonPlan: 'पाठ योजना (Lesson Plan)',
    demoPlan: 'प्रदर्शन योजना (Demo Plan)',
    monthlyPlan: 'मासिक योजना',
    yearlyPlan: 'वार्षिक योजना',
    monthlyAssess: 'मासिक मूल्यांकन',
    internalAssess: 'आंतरिक मूल्यांकन',
    examForm: 'परीक्षा फॉर्म',
    attendance: 'उपस्थिति',
    customForms: 'कस्टम रजिस्टर',
    logout: 'लॉग आउट',
    settings: 'सेटिंग्स',
    appName: 'आईटीआई इंस्ट्रक्टर एमएस',
    welcome: 'आपका स्वागत है',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    loading: 'लोड हो रहा है...',
    print: 'प्रिंट',
    generate: 'बनाएं',
    dailyDiary: 'दैनिक डायरी',
    instructorDashboard: 'प्रशिक्षक डैशबोर्ड',
    adminDashboard: 'एडमिन डैशबोर्ड',
    profilePending: 'प्रोफाइल लंबित',
    welcomeUser: 'स्वागत है, {name}!',
    contactAdminEmail: 'आपका प्रशिक्षक प्रोफाइल अभी तक इस खाते से जुड़ा नहीं है। कृपया अपने ईमेल का उपयोग करके अपनी प्रोफाइल लिंक करने के लिए एडमिन से संपर्क करें: ',
    gettingStarted: 'शुरुआत करें',
    profileLinkedInfo: 'एक बार आपकी प्रोफाइल लिंक हो जाने के बाद, आप यहां अपना ट्रेड असाइनमेंट, अनुभव विवरण और अन्य व्यावसायिक जानकारी देख पाएंगे।',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    tradeDept: 'ट्रेड/विभाग',
    qualification: 'योग्यता',
    experience: 'अनुभव',
    phoneNumber: 'फोन नंबर',
    joiningDate: 'शामिल होने की तिथि',
    myProfileDetails: 'मेरी प्रोफाइल विवरण',
    currentStatus: 'वर्तमान स्थिति',
    assignedTrade: 'सौंपा गया ट्रेड',
    profileUpToDateInfo: 'आपकी प्रोफाइल अप-टू-डेट है। यदि आपको कोई जानकारी बदलने की आवश्यकता है, तो कृपया आईटीआई एडमिन से संपर्क करें.',
    quickLinks: 'त्वरित लिंक',
    viewTradeSyllabus: 'ट्रेड सिलेबस देखें',
    attendanceRegister: 'उपस्थिति रजिस्टर',
    studentProgress: 'छात्र प्रगति',
    active: 'सक्रिय',
    years: 'वर्ष',
    notSpecified: 'निर्दिष्ट नहीं',
    dashboardOverview: 'डैशबोर्ड अवलोकन',
    welcomeAppInfo: 'आईटीआई इंस्ट्रक्टर मैनेजमेंट सिस्टम में आपका स्वागत है।',
    totalInstructors: 'कुल प्रशिक्षक',
    inactive: 'निष्क्रिय',
    tradesCovered: 'कवर किए गए ट्रेड्स',
    aboutSystem: 'सिस्टम के बारे में',
    systemDescription1: 'यह प्रणाली औद्योगिक प्रशिक्षण संस्थानों (ITI) में प्रशिक्षकों के प्रबंधन को सुव्यवस्थित करने के लिए डिज़ाइन की गई है।',
    systemDescription2: 'मुख्य विशेषताओं में शामिल हैं:',
    centralizedDb: 'केंद्रीकृत प्रशिक्षक डेटाबेस',
    tradeAllocation: 'ट्रेड-वार कर्मचारी आवंटन',
    statusTracking: 'रियल-टाइम स्टेटस ट्रैकिंग',
    rbac: 'सुरक्षित भूमिका-आधारित पहुंच नियंत्रण',
    quickActions: 'त्वरित कार्रवाई',
    addTradeInfo: 'नया ट्रेड जोड़ने की आवश्यकता है?',
    generateMonthlyReport: 'मासिक रिपोर्ट तैयार करें',
    contactAdmin: 'एडमिन से संपर्क करें',
    comingSoon: 'जल्द ही आ रहा है',
    instituteName: 'संस्थान का नाम',
    batch: 'बैच',
    lessonName: 'पाठ का नाम',
    lessonNo: 'पाठ संख्या',
    duration: 'अवधि',
    plannedDate: 'नियोजित तिथि',
    procedure: 'प्रक्रिया (Procedure)',
    infoPoints: 'सूचना बिंदु',
    visualAids: 'दृश्य सहायता',
    addRow: 'पंक्ति जोड़ें',
    deleteRow: 'पंक्ति हटाएं',
    aiGenerate: 'एआई जनरेट करें',
    savePlan: 'योजना सहेजें',
    updateRecord: 'रिकॉर्ड अपडेट करें',
    step: 'चरण',
    details: 'विवरण',
    back: 'पीछे',
    min: 'मिनट',
    hrs: 'घंटे',
    selectTrade: 'ट्रेड चुनें',
    district: 'जिला',
    objectives: 'उद्देश्य',
    skillsLearned: 'सीखे गए कौशल',
    toolsUsed: 'उपयोग किए गए उपकरण/सामग्री',
    motivation: 'प्रेरणा (Motivation)',
    presentation: 'प्रस्तुति',
    result: 'परिणाम/निष्कर्ष',
    studentInvolvement: 'छात्रों की भागीदारी',
    spotHints: 'स्पॉट संकेत',
    instructorPanel: 'प्रशिक्षक पैनल',
    administration: 'प्रशासन',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    // Set document lang for accessibility and fonts
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
